name: CICD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
# Postgres
  POSTGRESQL_VERSION: 17.4
  POSTGRESQL_DB: zimgo1012
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: password
  #Java
  JAVA_VERSION: 21

  #DockerHub
  DOCKER_HUB_USERNAME: zimgo1012

  #AWS
  AWS_REGION: ca-central-1
  EB_ENVIRONMENT_NAME: Springboot-React-Fullstack-env
  EB_APPLICATION_NAME: Springboot-React-Fullstack
  EB_DEPLOYMENT_PACKAGE: elasticbeanstalk/docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.4 
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
          text: 'CICD ongoing... :eyes:'
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL }}


      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin

      - name: Build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%-d.%-m.%Y.%-H.%-M.%-S')" >> $GITHUB_OUTPUT

      - name: Docker Login
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD}}

      - name: Maven Clean Package and Push To DockerHub
        working-directory: demo
        run: ./mvnw --no-transfer-progress clean package -P build-frontend -P jib-push-to-dockerhub -Dapp.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}}
      
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
          text: ':white_check_mark: pushed zimgo1012/springboot-react-fullstack:${{steps.build-number.outputs.BUILD_NUMBER}}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        
      - name: Update and commit app version in docker-compose.yml
        run: |
          BUILD_NUMBER=${{steps.build-number.outputs.BUILD_NUMBER}}
          echo -e "Current elasticbeanstalk/docker-compose.yml\n$(cat elasticbeanstalk/docker-compose.yml)"
          sed -i -E "s_(zimgo1012/springboot-react-fullstack:)([^ ]*)_\1${BUILD_NUMBER}_" elasticbeanstalk/docker-compose.yml
          echo -e "Updated demo/elasticbeanstalk/docker-compose.yml\n$(cat elasticbeanstalk/docker-compose.yml)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add elasticbeanstalk/docker-compose.yml
          git commit -m "new app version: ${BUILD_NUMBER}"
          git push

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
          text: ':white_check_mark: Deployment starting'
          
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

          
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@ebe3476a4ce991d54336935e75e78dd9d86f9408
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{env.AWS_REGION }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          deployment_package: ${{ env.EB_DEPLOYMENT_PACKAGE }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: Version ${{ steps.build-number.outputs.BUILD_NUMBER }} deployed via github action
          wait_for_deployment: 60

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{job.status}}
          fields: repo, message, commit, author, action, eventName, ref, workflow, job, took
          text: ':tada: :arrow_right: http://springboot-react-fullstack-env.eba-tc3tw6tv.ca-central-1.elasticbeanstalk.com/'
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL }}
        if: always()    